# Generated by Django 5.1.4 on 2025-01-04 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totaldespesasfixas',
            options={'ordering': ['-data_criação']},
        ),
        migrations.AlterModelOptions(
            name='totaldespesasvariaveis',
            options={'ordering': ['-data_criação']},
        ),
        migrations.AlterModelOptions(
            name='totalreceitas',
            options={'ordering': ['-data_criação']},
        ),
        migrations.AddField(
            model_name='totaldespesasfixas',
            name='data_criação',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='totaldespesasvariaveis',
            name='data_criação',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='totalreceitas',
            name='data_criação',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
